- hosts: all
  sudo: yes

  tasks:

      - name: Updating local repos
        apt: update_cache=yes

      - name: Installing RabbitMQ as broker
        apt: name=rabbitmq-server state=present

      - name: Installing Redis as backend
        apt: name=redis-server state=present

      - name: Installing Pip
        apt: name=python-pip

      - name: Installing Redis python package
        pip: name=redis

      - name: Installing Celery
        pip: name=celery

      - name: Installing Flower
        pip: name=flower

      - name: Copying 'flower/' to remote server
        sudo: no
        copy: src=flower/ dest=~/flower/
            
      - name: Starting rabbitmq-server
        service: name=rabbitmq-server state=started

      - name: Starting redis
        service: name=redis-server state=started

      - name: Binding redis to 0.0.0.0
        lineinfile: >
            dest=/etc/redis/redis.conf
            regexp="bind 127.0.0.1"
            line="bind 0.0.0.0"
            state=present

      - name: Setting password for reddis
        lineinfile: >
            dest=/etc/redis/redis.conf
            line="# require password bla"
            state=present

      - name: Starting celery worker
        sudo: no
        shell: screen -S celworker -d -m celery -A hardening.tasks worker --loglevel=info chdir=/home/ubuntu/flower

      - name: Starting flower
        sudo: no
        shell: screen -S flower -d -m flower --address=0.0.0.0 -A hardening.tasks --port=5555 --basic_auth=user:password chdir=/home/ubuntu/flower
